UCEP/Controllers/UCEPController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using UCEP.Common;
using UCEP.Models;
using static UCEP.Enums;

namespace UCEP.Controllers
{
    public class UCEPController : Controller
    {
        public UCEPController()
        {
            GlobalConfig.InitializeConnections(DatabaseType.MySql);
        }

        // GET: UCEP
        //[OutputCache(Duration = 60)]
        public ActionResult Index(string searchString, string catalogue, string hospital)
        {
            dynamic models = null;

            // clear list
            GlobalConfig.Clear();

            if (!string.IsNullOrEmpty(hospital))
            {
                hospital.SetHospital();
                ViewData["hospital"] = GlobalConfig.Hospital.Item2;
            }

            if (!string.IsNullOrEmpty(catalogue))
            {
                catalogue.SetCatalogue();
                ViewData["catalogue"] = catalogue;

                if (catalogue == Catalogue.FSCatalogue.ToString())
                {
                    ViewBag.Filter = "FSCodeNIEMS Or FSCodeHos";
                    GlobalConfig.FsCatalogueList = GlobalConfig.Connection.GetAllFsCatalogueByHospitalCode(GlobalConfig.Hospital.Item1);
                    models = GlobalConfig.FsCatalogueList;

                    if (!string.IsNullOrEmpty(searchString))
                    {
                        var model = GlobalConfig.Connection.GetFsCatalogueFromGlobalConfig(searchString);
                        GlobalConfig.FsCatalogueList.Clear();
                        GlobalConfig.FsCatalogueList = model;
                    }

                    ViewData["FsCatalogueList"] = GlobalConfig.FsCatalogueList;
                }
                else if (catalogue == Catalogue.DrugCatalogue.ToString())
                {
                    ViewBag.Filter = "HospDrugCode Or TMTID";
                    GlobalConfig.DrugCatalogueList = GlobalConfig.Connection.GetAllDrugCatalogue();
                    models = GlobalConfig.DrugCatalogueList;

                    if (!string.IsNullOrEmpty(searchString))
                    {
                        var model = GlobalConfig.Connection.GetDrugCatalogueFromGlobalConfig(searchString);
                        GlobalConfig.DrugCatalogueList.Clear();
                        GlobalConfig.DrugCatalogueList = model;
                    }

                    ViewData["DrugCatalogueList"] = GlobalConfig.DrugCatalogueList;
                }
            }


            return View();
        }

        // GET: UCEP/Details/5
        public ActionResult Details(int id)
        {
            var model = GlobalConfig.Connection.GetFsCatalogue(id);

            return View(model);
        }

        // GET: UCEP/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: UCEP/Create
        [HttpPost]
        public ActionResult Create(FsCatalogue fsCatalogue)
        {
            try
            {
                // TODO: Add insert logic here
                GlobalConfig.Connection.CreateFsCatalogue(fsCatalogue);

                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                return View();
            }
        }

        // GET: UCEP/Edit/5
        public ActionResult Edit(int id)
        {
            var model = GlobalConfig.Connection.EditFsCatalogue(id);

            return View(model);
        }

        // POST: UCEP/Edit/5
        [HttpPost]
        public ActionResult Edit(FsCatalogue fsCatalogue)
        {
            try
            {
                // TODO: Add update logic here
                GlobalConfig.Connection.EditFsCatalogue(fsCatalogue);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: UCEP/Delete/5
        public ActionResult Delete(int id)
        {
            var model = GlobalConfig.Connection.DeleteFsCatalogue(id);

            return View(model);
        }

        // POST: UCEP/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
                GlobalConfig.Connection.DeleteFsCatalogue(id, collection);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

UCEP/Views/UCEP/Create.cshtml
@model UCEP.Models.FsCatalogue

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>FsCatalogue</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.HospitalCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HospitalCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HospitalCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FSCodeNIEMS, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FSCodeNIEMS, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FSCodeNIEMS, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FSCodeHos, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FSCodeHos, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FSCodeHos, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Category, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Category, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Category, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Meaning, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Meaning, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Meaning, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Unit, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Unit, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Unit, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EffectiveDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EffectiveDate, new { htmlAttributes = new { @class = "form-control", placeholder = "yyyy-MM-dd" } })
                @Html.ValidationMessageFor(model => model.EffectiveDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Status, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ApprovalDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ApprovalDate, new { htmlAttributes = new { @class = "form-control", placeholder = "yyyy-MM-dd hh:mm:ss" } })
                @Html.ValidationMessageFor(model => model.ApprovalDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

UCEP/Views/UCEP/Delete.cshtml
@model UCEP.Models.FsCatalogue

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>FsCatalogue</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.HospitalCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HospitalCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FSCodeNIEMS)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FSCodeNIEMS)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FSCodeHos)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FSCodeHos)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Category)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Meaning)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Meaning)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Unit)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Unit)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EffectiveDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EffectiveDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ApprovalDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ApprovalDate)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

UCEP/Views/UCEP/Details.cshtml
@model UCEP.Models.FsCatalogue

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>FsCatalogue</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.HospitalCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HospitalCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FSCodeNIEMS)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FSCodeNIEMS)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FSCodeHos)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FSCodeHos)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Category)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Meaning)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Meaning)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Unit)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Unit)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EffectiveDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EffectiveDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ApprovalDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ApprovalDate)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

UCEP/Views/UCEP/Edit.cshtml
@model UCEP.Models.FsCatalogue

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>FsCatalogue</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.HospitalCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HospitalCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HospitalCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FSCodeNIEMS, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FSCodeNIEMS, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FSCodeNIEMS, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FSCodeHos, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FSCodeHos, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FSCodeHos, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Category, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Category, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Category, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Meaning, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Meaning, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Meaning, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Unit, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Unit, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Unit, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EffectiveDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EffectiveDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EffectiveDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Status, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ApprovalDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ApprovalDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ApprovalDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

UCEP/Views/UCEP/Index.cshtml
@model IEnumerable<UCEP.Models.FsCatalogue>

@using UCEP.Models;

@{
    ViewBag.Title = "Index";
}


<style type="text/css">
  /* Generic Styling, for Desktops/Laptops */
  table {
    width: 100%;
    border-collapse: collapse;
  }
  /* Zebra striping */
  tr:nth-of-type(odd) {
    background: #eee;
  }

  th {
    background: #333;
    color: white;
    font-weight: bold;
  }

  td, th {
    padding: 6px;
    border: 1px solid #ccc;
    text-align: left;
  }
  /*
    Max width before this PARTICULAR table gets nasty
    This query will take effect for any screen smaller than 760px
    and also iPads specifically.
    */
  @@media only screen and (max-width: 760px), (min-device-width: 768px) and (max-device-width: 1024px) {

    /* Force table to not be like tables anymore */
    table, thead, tbody, th, td, tr {
      /*display: block;*/
    }

      /* Hide table headers (but not display: none;, for accessibility) */
      thead tr {
        position: absolute;
        top: -9999px;
        left: -9999px;
      }

    tr {
      border: 1px solid #ccc;
    }

    td {
      /* Behave  like a "row" */
      border: none;
      border-bottom: 1px solid #eee;
      position: relative;
      padding-left: 50%;
    }

      td:before {
        /* Now like a table header */
        position: absolute;
        /* Top/left values mimic padding */
        top: 6px;
        left: 6px;
        width: 45%;
        padding-right: 10px;
        white-space: nowrap;
      }

      /*
     Label the data
     */
      td:before {
        content: attr(data-title);
      }
  }
</style>

<h2>List Item @GlobalConfig.Hospital.Item2</h2>

<span id="spanHos"></span>

@*<p>
      @Html.ActionLink("Create New", "Create")
  </p>*@


@using (Html.BeginForm("Index", "UCEP", FormMethod.Post, new { id = "dropdown", name = "dropdown" }))
{
  @Html.DropDownList("catalogue",
                           new SelectList(Enum.GetValues(typeof(Enums.Catalogue))),
                           "---Select Catalogue---",
                           new { @class = "form-control" })
  <br />

  @Html.DropDownList("hospital",
                      new SelectList(Enum.GetValues(typeof(Enums.Hospital))),
                      "---Select Hospital---",
                      new { @class = "form-control", onchange = "SelectedIndexChanged()" })
  <br />

        <p>
          @Html.TextBox("SearchString", ViewData.TemplateInfo.FormattedModelValue, new { @class = "form-control", placeholder = ViewBag.Filter })
          <input type="submit" value="Filter" />
        </p>
}

@*<form method="get" action="@Url.Action("Index")"
      data-ucep-ajax="true" data-ucep-target="#ucepList">
  <input type="radio" value=""/>
  <input type="search" name="searchTerm" data-ucep-autocomplete="@Url.Action("Autocomplete")" />
  <input type="submit" value="Search"/>
</form>*@

@if (GlobalConfig.Catalogue == Enums.Catalogue.FSCatalogue.ToString())
{
  <p>Number of Item : @GlobalConfig.FsCatalogueList.Count</p>
  @Html.Partial("_FSCatalogue", @GlobalConfig.FsCatalogueList)
}
else if (GlobalConfig.Catalogue == Enums.Catalogue.DrugCatalogue.ToString())
{
  <p>Number of Item : @GlobalConfig.DrugCatalogueList.Count</p>
  @Html.Partial("_DrugCatalogue", GlobalConfig.DrugCatalogueList)
}



<script type="text/javascript">

  function SelectedIndexChanged() {
    //Form post
    document.dropdown.submit();
  }

</script>